---
kind: pipeline
type: docker
name: default

steps:
- name: build
  image: golang:1.13
  commands:
    - make test
    - make build-static
  when:
    event: push
    branch: master

- name: cr
  image: plugins/docker
  settings:
    registry: cr.chuhlomin.com
    repo: cr.chuhlomin.com/utterson
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    context: ./cmd/utterson
    dockerfile: cmd/utterson/Dockerfile
    tags:
      - ${DRONE_COMMIT}
      - latest
  when:
    event: push
    branch: master

trigger:
  branch:
    - master

image_pull_secrets:
  - dockerconfigjson
