name: GenBlog
description: Generate a static blog from Markdown files

author: Konstantin Chukhlomin <mail@chuhlomin.com>

branding:
  icon: book
  color: purple

inputs:
  title:
    description: Title of the blog
    required: true
  short_description:
    description: Short description of the blog
    required: true
  author:
    description: Author of the blog
    required: true
  source_directory:
    description: Path to directory with Markdown filenames
    required: false
    default: "."
  output_directory:
    description: Path to output directory
    required: false
    default: "output"
  templates_directory:
    description: Path to templates directory
    required: false
    default: "templates"
  template_post:
    description: Name of the template for posts
    required: false
    default: "post.html"
  templates:
    description: >
      Comma-separated templates filenames that will be processed
      in addition to posts
    required: false
    default: "index.html,404.html"
  allowed_file_extensions:
    description: >
      Comma-separated templates extensions that will be copied as is
      to output directory
    required: false
    default: ".jpeg,.jpg,.png,.mp4,.pdf"
  default_language:
    description: Default language for the blog
    required: false
    default: "en"
  comments_enabled:
    description: Enable typography
    required: false
    default: "false"
  comments_site_id:
    description: Site ID for Remark42 comments
    required: false
    default: ""
  show_drafts:
    description: Show drafts
    required: false
    default: "false"
  thumb_path:
    description: Path to thumbnails directory
    required: false
    default: "thumb"
  thumb_max_width:
    description: Max width of thumbnails
    required: false
    default: "140"
  thumb_max_height:
    description: Max height of thumbnails
    required: false
    default: "140"
  search_enabled:
    description: Enable search
    required: false
    default: "false"
  search_path:
    description: Path to search index file
    required: false
    default: "index.bleve"

runs:
  using: docker
  image: 'docker://chuhlomin/genblog:v0.5'
