name: GenBlog
description: Generate a static blog from Markdown files

author: Konstantin Chukhlomin <mail@chuhlomin.com>

branding:
  icon: book
  color: purple

inputs:
  base_path:
    description: Base path for all generated URLs
    required: false
  source_directory:
    description: Path to directory with Markdown filenames
    required: false
    default: "."
  static_directory:
    description: Path to directory with static files, to copy to `output_directory`
    required: false
  output_directory:
    description: Path to output directory
    required: false
    default: "output"
  allowed_file_extensions:
    description: Comma-separated list of allowed file extensions that will be copied as is
    required: false
    default: ".jpeg,.jpg,.png,.mp4,.pdf"
  templates_directory:
    description: Path to templates directory
    required: false
    default: "_templates"
  default_template:
    description: Filename of the default template
    required: false
    default: "_post.html"
  default_language:
    description: Default language for the blog
    required: false
    default: "en"
  comments_enabled:
    description: Enable comments
    required: false
    default: "false"
  comments_site_id:
    description: Site ID for Remark42 comments
    required: false
    default: ""
  show_drafts:
    description: Show drafts
    required: false
    default: "false"
  thumb_path:
    description: Path to thumbnails directory
    required: false
    default: "thumb"
  thumb_max_width:
    description: Max width of thumbnails
    required: false
    default: "140"
  thumb_max_height:
    description: Max height of thumbnails
    required: false
    default: "140"
  search_enabled:
    description: Enable search
    required: false
    default: "false"
  search_url:
    description: URL to search service
    required: false
  search_path:
    description: Path to search index file
    required: false
    default: "index.bleve"

runs:
  using: docker
  image: 'docker://chuhlomin/genblog:v1.0-rc5'
