name: GenBlog
description: Generate a static blog from markdown files

author: Konstantin Chukhlomin <mail@chuhlomin.com>

branding:
  icon: book
  color: purple

inputs:
  title:
    description: Title of the blog
    required: true
  short_description:
    description: Short description of the blog
    required: true
  author:
    description: Author of the blog
    required: true
  source_directory:
    description: Path to directory with Markdown files, default "."
    required: false
  output_directory:
    description: Path to output directory, default "output"
    required: false
  templates_directory:
    description: Path to templates directory, default "templates"
    required: false
  templates:
    description: >
      Comma-separated templates filenames that will be processed
      in addition to posts, default "index.html,404.html"
    required: false
  allowed_file_extensions:
    description: >
      Comma-separated templates extensions that will be copied as is
      to output directory, default ".jpeg,.jpg,.png,.mp4,.pdf"
    required: false
  typography_enabled:
    description: Enable typography, default "false"
    required: false
  comments_enabled:
    description: Enable typography, default "false"
    required: false
  comments_site_id:
    description: Site ID for Remark42 comments, default ""
    required: false
  show_social_sharing_buttons:
    description: Enable social sharing buttons, default "false"
    required: false
  show_drafts:
    description: Show drafts, default "false"
    required: false

outputs:
  result:
    description: Rendered file content

runs:
  using: docker
  image: 'docker://chuhlomin/genblog:v0.3'
