name: main

on:
  push:
    branches:
      - main
      
env:
  DOCKER_IMAGE: chuhlomin/genblog

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to CR
        uses: docker/login-action@v1
        with:
          username: chuhlomin
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Prepare Docker tags and labels
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ${{ env.DOCKER_IMAGE }}
          tag-sha: true

      - name: Build and push to CR
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: chuhlomin/genblog@v0.1
          labels: ${{ steps.docker_meta.outputs.labels }}
