name: main

on:
  push:
    branches:
      - main
      
env:
  DOCKER_IMAGE: chuhlomin/genblog

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to CR
        uses: docker/login-action@v1
        with:
          username: chuhlomin
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: {{ env.DOCKER_IMAGE }}
          tags: v0.1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}